// <auto-generated />
namespace Electronica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ElectronicaV6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ElectronicaV6));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300634185_ElectronicaV6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
